//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Simulations = new HashSet<Simulation>();
        }
    
        public int ProjectID { get; set; }
        public string ConnectionString { get; set; }
        public string ArchiveURI { get; set; }
    
        public virtual ICollection<Simulation> Simulations { get; set; }
    }
}
