//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulation
    {
        public Nullable<decimal> RunID { get; set; }
        public string WorkerID { get; set; }
        public string Status { get; set; }
        public Nullable<int> Repitition { get; set; }
        public string SimulationId { get; set; }
        public int rowid { get; set; }
        public Nullable<int> projectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
